story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story5.urls')),
    path('story5/', include('story5.urls')),
    path('story3/', include('story3.urls')),
    path('story1/', include('story1.urls')),
]

story1/urls.py
from django.urls import path
from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.index, name='index'),
]

story3/urls.py
from django.urls import path

from . import views

app_name = 'story3'

urlpatterns = [
    path('', views.index, name='index'),
    path('secret/', views.secret, name='secret'),
]

story5/urls.py
from django.urls import path

from . import views

app_name = 'story5'

urlpatterns = [
    path('', views.index, name='index'),
    path('courses/', views.index, name='index'),
    path('add/', views.add, name='add'),
    path('update/<str:pk>/', views.update, name='update'),
    path('delete/<str:pk>/', views.delete, name='delete'),
    path('show/<str:pk>/', views.show, name='show')
]

story1/models.py
from django.db import models

# Create your models here.

story3/models.py
from django.db import models

# Create your models here.

story5/models.py
from django.db import models

class Courses(models.Model):
    course = models.CharField(max_length=50)
    lecturer = models.CharField(max_length=50)
    sks = models.IntegerField()
    desc = models.TextField(max_length=350)
    term = models.CharField(max_length=20)
    room = models.CharField(max_length=10)

    def __str__(self):
        return self.course

story5/forms.py
from django import forms
from . import models

class CoursesForm(forms.ModelForm):
    class Meta:
        model = models.Courses
        fields = ("course", "lecturer", "sks", "desc", "term", "room")

    course = forms.CharField(label='Course Name', widget=forms.TextInput(attrs=
    {
        'type' : 'text',
        'placeholder' : 'Course Name',
        'required' : 'True',
    }))

    lecturer = forms.CharField(label='Lecturer Name', widget=forms.TextInput(attrs=
    {
        'type' : 'text',
        'placeholder' : 'Lecturer Name',
        'required' : 'True',
    }))

    sks = forms.IntegerField(label='Credit per Term', min_value=1, max_value=24, widget=forms.NumberInput(attrs=
    {
        'type' : 'text',
        'required' : 'True',
    }))

    desc = forms.CharField(label='Description', widget=forms.Textarea(attrs=
    {
        'rows' : '4',
        'type' : 'text',
        'placeholder' : 'Description',
        'required' : 'True',
    }))

    term = forms.CharField(label='Term', widget=forms.Select(attrs=
    {
        'required' : 'True',
    }, choices=(
        ("Gasal 2020/2019", "Gasal 2020/2019"),
        ("Genap 2019/2020", "Genap 2019/2020"),
        ("Gasal 2019/2020", "Gasal 2019/2020"),
        ("Lainnya", "Lainnya"),
    )))

    room = forms.CharField(label='Room', widget=forms.TextInput(attrs=
    {
        'type' : 'text',
        'placeholder' : 'Room',
        'required' : 'True',
    }))

story1/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'story1/index.html')

story3/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'story3/index.html')

def secret(request):
    return render(request, 'story3/secret.html')

story5/views.py
from django.shortcuts import render, redirect
from story5.forms import CoursesForm
from story5.models import Courses

def index(request):
    data = Courses.objects.all()
    context = {
        "data" : data,
    }
    return render(request, "story5/index.html", context)

def add(request):
    form = CoursesForm(request.POST or None)
    if form.is_valid() and request.method == "POST":
        form.save()
        return redirect('/add')
    context = {
        "form" : form,
        "task" : "add",
    }
    return render(request, "story5/add.html", context)

def update(request, pk):
    course = Courses.objects.get(id=pk)
    form = CoursesForm(instance=course)
    if request.method == "POST":
        form = CoursesForm(request.POST, instance=course)
        if form.is_valid():
            form.save()
            return redirect('/')
    context = {
        "form" : form,
        "task" : "update",
    }
    return render(request, 'story5/add.html', context)

def delete(request, pk):
    course = Courses.objects.get(id=pk)
    if request.method == "POST":
        course.delete()
        return redirect('/')

def show(request, pk):
    course = Courses.objects.get(id=pk)
    context = {
        "course" : course
    }
    return render(request, 'story5/courses.html', context)
    

story1/templates/story1/_navbar.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="/static/story1/navbar.css">
        <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap" rel="stylesheet">
    </head>
    <body>
        <div id="navbar">
            <ul>
                <li id="irfancen"><a href="/">irfancen</a></li>
                <div class="social">
                    <li><a href="https://youtube.com/channel/UCUBJWyC1qJkg-t70SDTBBYQ" target="_blank"><img src="/static/story1/icons/youtube.png"></a></li>
                    <li><a href="http://linkedin.com/in/mirfanjunaidi" target="_blank"><img src="/static/story1/icons/linkedin.png"></a></li>
                    <li><a href="http://instagram.com/irfancen" target="_blank"><img src="/static/story1/icons/instagram.png"></a></li>
                    <li><a href="https://twitter.com/irfancen_" target="_blank"><img src="/static/story1/icons/twitter.png"></a></li>
                    <li><a href="http://facebook.com/irfancen" target="_blank"><img src="/static/story1/icons/facebook.png"></a></li>
                </div>
                <div class="links">
                    <li><a href="#Profile" onclick="smoothScroll(document.getElementById('profile'))">Profile</a></li>
                    <li><a href="#About" onclick="smoothScroll(document.getElementById('about'))">About Me</a></li>
                    <li><a href="#Home" onclick="smoothScroll(document.getElementById('home'))">Home</a></li>
                </div>
            </ul>
        </div>
        <script>
            var prevScrollpos = window.pageYOffset;
            window.onscroll = function() {
            var currentScrollPos = window.pageYOffset;
                if (prevScrollpos >= currentScrollPos) {
                    document.getElementById("navbar").style.top = "0";
                }
                else {
                    document.getElementById("navbar").style.top = "-100px";
              }
              prevScrollpos = currentScrollPos;
            }
            </script>
            <script src="{% static '/story1/navbar.js' %}"></script>
    </body>
</html>

story1/templates/story1/index.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Story 1 - M. Irfan Junaidi</title>
        <link rel="stylesheet" href="{% static 'story1/styles.css' %}">
    </head>
    <body>
        {% include 'story1/_navbar.html' %}
        <div class="index">
            <div class="home" id="home">
                <h3>Hi!</h3>
            </div>
            <div class="about hide" id="about">
                <div class="a-left">
                    <div class="border">
                        <h1>About</h1>
                        <h1>Me</h1>
                    </div>
                    <img src="/static/story1/me.png" alt="Me">
                </div>
                <div class="a-right">
                    <p>My name is Irfan and i'm a Computer Science Student in University of Indonesia.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas non odio quam. Nunc ut turpis posuere, eleifend risus sollicitudin, ultrices nisl. Ut laoreet iaculis ante, vel auctor justo volutpat sit amet. Ut sagittis, velit sed pharetra commodo, magna libero rhoncus risus, ut efficitur urna tellus a lectus.</p>
                </div>
            </div>
            <div class="profile hide" id="profile">
                <h1>Profile</h1>
                <div class="p-table">
                    <table>
                        <tr>
                            <th>Full Name</th>
                            <th>NPM</th>
                            <th>Education</th>
                        </tr>
                        <tr>
                            <td>Muhammad Irfan Junaidi</td>
                            <td>1906293202</td>
                            <td rowspan="3">
                                <ul>
                                    <li>SMA Negeri 38 Jakarta</li>
                                    <li>SMP Citra Alam</li>
                                    <li>SD Citra Alam</li>
                                </ul>
                            </td>
                        </tr>
                        <tr>
                            <th>Class of</th>
                            <th>Hobby</th>
                        </tr>
                        <tr>
                            <td>2019</td>
                            <td>
                                <ul>
                                    <li>Coding</li>
                                    <li>Gaming</li>
                                </ul>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <script src="{% static '/story1/home.js' %}"></script>
    </body>
</html>

story3/templates/story3/_navbar.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="/static/story3/styles.css">
        <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap" rel="stylesheet">
    </head>
    <body>
        <div class="navbar" id="navbar">
            <ul>
                <li id="irfancen"><a href="/">irfancen</a></li>
                <div class="links">
                    <li><a id="nav-but" onclick="navbar()">≡</a></li>
                    <div id="cont-nav">
                        <li><a href="/#home" onclick="smoothScroll(document.getElementById('home'))">Home</a></li>
                        <li><a href="/#about" onclick="smoothScroll(document.getElementById('about'))">About</a></li>
                        <li><a href="/#profile" onclick="smoothScroll(document.getElementById('profile'))">Profile</a></li>
                        <li><a href="/#contact" onclick="smoothScroll(document.getElementById('contact'))">Contact</a></li>
                    </div>
                </div>
            </ul>
        </div>
        <script src="{% static 'story3/navbar.js' %}"></script>
    </body>
</html>

story3/templates/story3/index.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Story 3 - M. Irfan Junaidi</title>
    </head>
    <body>
        {% include 'story3/_navbar.html' %}
        <div class="index">
            <section id="home">
                <h1>Hi!</h1>
            </section>
            <section id="about">
                <h2 id="a-mobile">About Me</h2>
                <div class="cont-about">
                    <div class="a-left">
                        <div class="pict">
                            <img src="{% static 'story3/src/me.jpg' %}">
                        </div>
                    </div>
                    <div class="a-right">
                        <h2>About Me</h2>
                        <p>My name is Muhammad Irfan Junaidi and I’m currently on the 3rd term of studying Computer Science at Universitas Indonesia. I love to code or game in my spare time.</p>
                    </div>
                </div>
            </section>
            <section id="profile">
                <h2>Profile</h2>
                <div class="edu prof">
                    <h3>Education</h3>
                    <div class="e-cont">
                        <div class="cont"><span>Primary<br>School</span><p>SD Citra Alam Ciganjur<br>2007-2013</p></div>
                        <img class="ar" id="ar1" src="{% static 'story3/src/arrow.png' %}">
                        <div class="cont"><span>Middle<br>School</span><p>SMP Citra<br>Alam Ciganjur<br>2013-2016</p></div>
                        <img class="ar" id="ar2" src="{% static 'story3/src/arrow.png' %}">
                        <div class="cont"><span>High<br>School</span><p>SMA Negeri 38 Jakarta<br>2016-2019</p></div>
                        <img class="ar" id="ar3" src="{% static 'story3/src/arrow.png' %}">
                        <div class="cont"><span>Bachelor of Computer Science</span><p>Universitas Indonesia<br>2019-2023</p></div>
                    </div>
                </div>
                <div class="skill prof">
                    <h3>Skills</h3>
                    <div class="s-cont">
                        <div class="cont"><img src="{% static 'story3/src/python.png' %}" alt="Python"><p>Python</p></div>
                        <div class="cont"><img src="{% static 'story3/src/java.png' %}" alt="Java"><p>Java</p></div>
                        <div class="cont"><img src="{% static 'story3/src/html.png' %}" alt="HTML"><p>HTML</p></div>
                        <div class="cont"><img src="{% static 'story3/src/css.png' %}" alt="CSS"><p>CSS</p></div>
                    </div>
                </div>
                <div class="exp prof">
                    <h3>Experience</h3>
                    <div class="cont"><span>Front-End<br>Web<br>Developer</span><br><p>BETIS Fasilkom UI 2020</p></div>
                    <div class="cont"><span>Teaching Assistant for DDP1</span><br><p>Universitas Indonesia</p></div>
                    <div class="cont"><span>Staff of Supervision Division</span><br><p>DPM Fasilkom<br>UI 2020</p></div>
                    <div class="cont"><span>Mentor and Academic<br>Staff</span><br><p>Dasar-Dasar Pemrograman 0</p></div>
                </div>
            </section>
            <section id="contact">
                <h2>Contact</h2>
                <div class="c-cont">
                    <a href="http://twitter.com/irfancen_/" target="_blank"><img src="{% static 'story3/src/twitter.png' %}" alt="Twitter"></a>
                    <a href="http://instagram.com/irfancen/" target="_blank"><img src="{% static 'story3/src/instagram.png' %}" alt="Instagram"></a>
                    <a href="http://linkedin.com/in/mirfanjunaidi/" target="_blank"><img src="{% static 'story3/src/linkedin.png' %}" alt="LinkedIn"></a>
                    <a href="http://github.com/irfancen/" target="_blank"><img src="{% static 'story3/src/github.png' %}" alt="Github"></a>
                    <a href="http://gitlab.com/irfancen/" target="_blank"><img src="{% static 'story3/src/gitlab.png' %}" alt="Gitlab"></a>
                </div>
            </section>
        </div>
    </body>
</html>

story3/templates/story3/secret.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>This is a secret Website</title>
        <link rel="stylesheet" href="/static/story3/styles.css">
    </head>
    <body>
        {% include 'story3/_navbar.html' %}
        <div class="index">
            <div class="cont-video">
                <div id="youtube-player"
                data-video="y8sSIGon3Yc"  
                data-height="480"
                data-width="853">
                </div>
            </div>
        </div>
            
        <script src="https://www.youtube.com/iframe_api"></script>
        <script type="text/javascript">
            function onYouTubeIframeAPIReady() {
                var ctrlq = document.getElementById("youtube-player");
                var done = false;
                var player = new YT.Player('youtube-player', {
                height: '100%',
                width: '100%',
                playerVars: {
                    rel: 0,
                    controls: 0,
                    disablekb: 1,
                },
                events: {
                    'onReady': function(e) {
                    e.target.cueVideoById({
                        videoId: ctrlq.dataset.video,  
                        startSeconds: 103.5,
                        endSeconds: 109.5,
                    });
                    e.target.playVideo();
                    },
                }
                });
            }
        </script>
    </body>
</html>

story3/templates/story3/test.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Hello Bulma!</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
    </head>
    <body>
        <nav class="navbar" role="navigation" aria-label="main navigation">
            <div class="navbar-brand">
                <a class="navbar-item" href="https://bulma.io">
                    <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
                </a>
          
                <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                </a>
            </div>
          
            <div id="navbarBasicExample" class="navbar-menu">
                <div class="navbar-start">
                    <a class="navbar-item">Home</a>
                    <a class="navbar-item">Documentation</a>
          
                    <div class="navbar-item has-dropdown is-hoverable">
                        <a class="navbar-link">More</a>
          
                        <div class="navbar-dropdown">
                            <a class="navbar-item">About</a>
                            <a class="navbar-item">Jobs</a>
                            <a class="navbar-item">Contact</a>
                            <hr class="navbar-divider">
                            <a class="navbar-item">Report an issue</a>
                        </div>
                    </div>
                </div>   
            </div>
          </nav>
    </body>
</html>

story5/templates/story5/_navbar.html
<!DOCTYPE html>
{% load static %}
<html>
	<head>
    <meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
		<link rel="stylesheet" href="{% static 'story5/styles.css' %}">
		<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <title>Story 5 - M. Irfan Junaidi</title>
	</head>
	<body>
		<nav class="navbar navbar-expand-lg navbar-dark sticky-top" id="navbar" style="background-color: rgb(56, 174, 220)">
			<a class="navbar-brand pl-5" href="/">irfancen</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="navbarNav">
				<hr class="mt-0 mb-0 bg-light">
				<ul class="navbar-nav mt-2 mt-lg-0 ml-auto mr-5">
					<li class="nav-item">
						<a class="nav-link" id="co" href="/">Courses</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" id="ac" href="/add">Add Course</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="/story1">Story 1</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="/story3">Story 3</a>
					</li>
				</ul>
			</div>
		</nav>
		{% block content %}
		{% endblock content %}
		<script src="{% static 'story5/navbar.js' %}"></script>
		<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
		<script>
			$('.navbar-nav .nav-link').click(function(){
			$('.navbar-nav .nav-link').removeClass('active');
			$(this).addClass('active');})
		</script>
	</body>
</html>

story5/templates/story5/add.html
{% extends 'story5/_navbar.html' %}
{% block content %}
{% load crispy_forms_tags %}
<div class="container">	
  <div class="row justify-content-center">
    <div class="col-8">
      {% if task == 'add' %}
        <h1 class="mt-4">Add Course</h1>
      {% else %}
        <h1 class="mt-4">Update Course</h1>
      {% endif %}
      <hr class="mt-0 mb-4">
      <form method="POST" class="is-valid">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Save</button>
      </form>
    </div>
  </div>
</div>
{% if task == 'add' %}
<script>
  $('#ac').addClass('active');
</script>
{% endif %}
{% endblock content %}

story5/templates/story5/courses.html
{% extends 'story5/_navbar.html' %}
{% block content %}
<div class="container">
  <div class="row-lg justify-content-center">
    <div class="col-8 pt-2" style="display: block; max-width: 90%;">
      <div style="overflow-wrap: break-word;">
        <h1 class="text-break mt-4">{{ course.course }}</h1>
      </div>
      <hr class="mt-0 mb-5">
      <div class="row mb-4">
        <div class="col-8">
          <h2 class="font-weight-bold">Lecturer</h2>
          <div style="display: block; max-width: 100%; overflow-wrap: break-word;">
            <h4 class="text-capitalize text-break">{{ course.lecturer }}</h4>
          </div>
        </div>
        <div class="col-4">
          <h2 class="font-weight-bold">SKS</h2>
          <h4>{{ course.sks }}</h4>
        </div>
      </div>
      <div class="row mb-4">
        <div class="col-8">
          <h2 class="font-weight-bold">Term</h2>
          <h4>{{ course.term }}</h4>
        </div>
        <div class="col-4">
          <h2 class="font-weight-bold">Room</h2>
          <h4>{{ course.room }}</h4>
        </div>  
        <div class="ml-3 mt-4" style="display: block; max-width: 100%; overflow-wrap: break-word;">
          <h2 class="font-weight-bold">Description</h2>
          <h4 class="text-break">{{ course.desc }}</h4>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

story5/templates/story5/index.html
<!DOCTYPE html>
{% load static %}
<html>
  <body>
    {% include 'story5/_navbar.html' %}
    <div class="container">	
      <div class="row justify-content-center">
        <div class="col-8 pt-2">
          <h1 class="mt-4">Courses</h1>
          <hr class="mt-0 mb-4">
        </div>
        {% if data.first != None %}
        <table class="table table-striped table-light table-responsive-lg mb-4">
          <tr style="background-color: rgb(56, 174, 220); color: white;">
            <th scope="col" class="mw-100">Course Name</th>
            <th scope="col" class="mw-100">Lecturer Name</th>
            <th scope="col">SKS</th>
            <th scope="col">Term</th>
            <th scope="col">Room</th>
            <th scope="col" class="text-center w-auto">Action</th>
          </tr>
          {% for course in data %}
            <tr>
              <td><a class="text-dark" href="{% url 'story5:show' course.id %}">{{ course.course }}</a></td>
              <td>{{ course.lecturer }}</td>
              <td>{{ course.sks }}</td>
              <td>{{ course.term }}</td>
              <td>{{ course.room }}</td>
              <td>
                <div class="row-lg d-flex justify-content-center">
                  <a class="btn btn-primary btn-sm mx-1" href="{% url 'story5:update' course.id %}">
                    <span class="material-icons">edit</span>
                  </a>
                  <form action="{% url 'story5:delete' course.id %}" method="POST">
                    {% csrf_token %}
                    <button class="btn btn-danger btn-sm mx-1" type="submit">
                      <span class="material-icons">delete</span>
                    </button>
                  </form>
                </div>
              </td>
            </tr>
          {% endfor %}
        </table>
        {% else %}
        <div class="col-8 text-black-50">
          <h4>You have no courses yet...😄</h4>
        </div>
        {% endif %}
      </div>
    </div>
    <script>
      $("#co").addClass('active');
    </script>
  </body>
</html>